### ISSUE TITLE
Should we restrict items to only be on one list or can an item be on multiple lists?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/time-mvp-phoenix#12]
At present the code is setup such that a `list` can `has_many :items`
but an `item` can only `has_one :list` ... 
This is operating under the _assumption_ that an `item` can only be added/belong to _one_ `list`.
Can we envisage a scenario where we would want to add an `item` to multiple lists?

For example: 
would we want to add an item to the todo list of two different people?
or would we have a "shared" list whereby two (_or more_) people can view the same list?
ultimately an item can/should only be _assigned_ to a _single_ person for accountability,
but imagine two people were _pair-programming_ on a feature, 
we would want them to be able to start two _independent_ timers related to the single item?
Or would we _copy_ (_make a duplicate_) of the item? 
I personally prefer the idea of being able to add the _same_ (_todo_) `item` to the individual daily todo list of two _separate_ people and allow them to _both_ log time against that `item`. 

Thoughts are very welcome on this.

**Comment by iteles** [comment]
Totally agree ☺️ I can foresee at least two future situations where this might also be useful: 
+ Adding the same to do to multiple lists owned by the same person (initial functionality limitations might mean someone adds something to their to do list that they also want to put on a weekly list)
+ Repeating todos, scheduled to appear in the list automatically ever my x amount of time
