### ISSUE TITLE
ERROR 42703 (undefined_column)

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/time-mvp-phoenix#6]
attempting to view items on localhost http://localhost:4000/items I get the following Error:
![image](https://user-images.githubusercontent.com/194400/61242275-32490280-a73d-11e9-92ee-1bc78361f6a4.png)

```
ERROR 42703 (undefined_column) column i0.list_id does not exist
```

Investigating now. 🔍

**Comment by RobStallion** [comment]
@nelsonic have you solved this issue yet? 

I haven't had a chance to look into this but from memory, this look like the error you get when you have not run all the migration files.

**Comment by nelsonic** [comment]
@RobStallion indeed that is what it appears to be. 👍 
after running `mix ecto.drop && mix ecto.create && mix ecto.migrate` it works. ✅ 
Thanks. 🥇
